# Generated by Django 5.1.3 on 2024-11-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.producto')),
                ('precio_total', models.FloatField()),
                ('id_factura', models.CharField(max_length=50, unique=True)),
                ('iva', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('productos', models.ManyToManyField(related_name='facturas', to='api.producto')),
            ],
            bases=('api.producto',),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('Codigo_proveedor', models.CharField(max_length=50, unique=True)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre_representante', models.CharField(max_length=100)),
                ('carrito_compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.carritocompra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
