# Generated by Django 5.1.3 on 2024-11-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_proveedor_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Codigo_proveedor',
            field=models.CharField(max_length=50),
        ),
    ]
