# Generated by Django 5.1.3 on 2024-11-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_proveedor_codigo_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_factura',
            field=models.CharField(max_length=50),
        ),
    ]
